inherit: 
    - models/tiny.yaml
    - wandb.yaml

model:
    n_dims: 20
    n_positions: 41

training:
    task: piecewise_linear_vector_regression
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 1000
    keep_every_steps: 100000
    train_steps: 500001
    curriculum:
        dims:
            start: 5
            end: 20
            inc: 1
            interval: 2000
        points:
            start: 11
            end: 41
            inc: 2
            interval: 2000

out_dir: ../models/piecewise_linear_vector_regression

wandb:
    name: "piecewise_linear_vector_regression"
