config: conf/piecewise_scalar.yaml
inherit:
- /content/gdrive/MyDrive/cs282/in-context-learning/conf/models/tiny.yaml
- /content/gdrive/MyDrive/cs282/in-context-learning/conf/wandb.yaml
model:
  family: gpt2
  n_dims: 1
  n_embd: 64
  n_head: 2
  n_layer: 3
  n_positions: 41
out_dir: ../models/piecewise_linear_regression/1db8b84f-4865-4dc0-94b9-376aa84984ec
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 1
      inc: 1
      interval: 2000
      start: 1
    points:
      end: 41
      inc: 2
      interval: 2000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: piecewise_linear_regression
  task_kwargs: {}
  train_steps: 500001
wandb:
  entity: qianyu2025-university-of-california-berkeley
  log_every_steps: 100
  name: piecewise_linear_regression
  notes: Experiment with piecewise linear function.
  project: in-context-training
